[package]
name = "sbot"
version = "0.1.0"
authors = ["Nguyen Thai <shiroemon279@gmail.com>"]
edition = "2018"


[dependencies]
serenity = "0.10"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = "0.2"
eyre = "0.3"
dotenv = "0.15.0"
ddg = { path = "ddg" }
color-eyre = "0.5"
tokio = { version = "1", features = ["full"] }
